// Generated by CoffeeScript 1.9.0
var IStorage, QLocalStorage, QManager, QRelation,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

(function() {
  return this.uniqid = function(pr, en) {
    var result, us;
    pr = pr || "";
    en = en || false;
    result = void 0;
    us = void 0;
    this.seed = function(s, w) {
      s = parseInt(s, 10).toString(16);
      if (w < s.length) {
        return s.slice(s.length - w);
      } else {
        if (w > s.length) {
          return new Array(1 + (w - s.length)).join("0") + s;
        } else {
          return s;
        }
      }
    };
    result = pr + this.seed(parseInt(new Date().getTime() / 1000, 10), 8) + this.seed(Math.floor(Math.random() * 0x75bcd15) + 1, 5);
    if (en) {
      result += (Math.random() * 10).toFixed(8).toString();
    }
    return result;
  };
})();

IStorage = (function() {
  function IStorage() {
    this.initStorage();
  }

  IStorage.prototype.initStorage = function() {
    throw false;
  };

  IStorage.prototype.get = function(key) {
    throw false;
  };

  IStorage.prototype.set = function(key, val) {
    throw false;
  };

  IStorage.prototype["delete"] = function(key) {
    throw false;
  };

  IStorage.prototype.getStorage = function() {
    throw false;
  };

  return IStorage;

})();

QLocalStorage = (function(_super) {
  __extends(QLocalStorage, _super);

  function QLocalStorage() {
    return QLocalStorage.__super__.constructor.apply(this, arguments);
  }

  QLocalStorage.prototype.storage = null;

  QLocalStorage.prototype.initStorage = function() {
    var error;
    try {
      this.storage = localStorage;
    } catch (_error) {
      error = _error;
      console.log(error);
    }
    return null;
  };

  QLocalStorage.prototype.getStorage = function() {
    return this.storage;
  };

  QLocalStorage.prototype.get = function(key) {
    return JSON.parse(this.storage.getItem(key));
  };

  QLocalStorage.prototype.set = function(key, val) {
    this.storage.setItem(key, JSON.stringify(val));
    return null;
  };

  QLocalStorage.prototype["delete"] = function(key) {
    this.storage.removeItem(key);
    return null;
  };

  return QLocalStorage;

})(IStorage);

QManager = (function() {
  QManager.prototype.storage = null;

  QManager.prototype.instance = null;

  QManager.prototype.relation = null;

  function QManager() {
    if (this.storage == null) {
      throw false;
    }
    this.relation = new QRelation(this.storage);
    this;
  }

  QManager.prototype.SetStorage = function(IStorage) {
    this.storage = IStorage;
    return null;
  };

  QManager.prototype.GetInstance = function() {
    if (this.instance != null) {
      return this.instance;
    } else {
      this.instance = new this.constructor();
      return this.instance;
    }
  };

  QManager.prototype.Create = function(json) {
    var __id;
    if (__id = this.relation.newRow()) {
      this.storage.set(__id, json);
      return __id;
    }
    return false;
  };

  QManager.prototype.Read = function(__id) {
    if (this.relation.findById(__id) === true) {
      return this.storage.get(__id);
    }
    return false;
  };

  QManager.prototype.Update = function(__id, json) {
    var row;
    if (row = this.Read(__id)) {
      this.storage.set(__id, json);
      return true;
    }
    return false;
  };

  QManager.prototype.Delete = function(__id) {};

  return QManager;

})();

$(function() {
  var book, qls;
  qls = new QLocalStorage();
  QManager.prototype.SetStorage(qls);
  book = {
    'author': 'a1',
    'year': 'y1',
    'title': 't1',
    'countPages': 'cp1'
  };
  QManager.prototype.GetInstance().Create(book);
  console.log(QManager.prototype.GetInstance().Read('book_5527b1afb40b0'));
  book.title = 't1_new';
  console.log(QManager.prototype.GetInstance().Update('book_5527b1afb40b0', book));
});

QRelation = (function() {
  QRelation.prototype.storage = null;

  QRelation.prototype.KEY = 'relation';

  function QRelation(_at_storage) {
    this.storage = _at_storage;
    if (this.storage.get(this.KEY) == null) {
      this.storage.set(this.KEY, []);
    }
  }

  QRelation.prototype.newRow = function() {
    var relation, __id;
    __id = uniqid('book_');
    relation = this.storage.get(this.KEY);
    if ((relation == null) || relation.length === 0) {
      relation = [];
    }
    if (relation.length !== 0) {
      relation = relation;
    }
    relation.push(__id);
    this.storage.set(this.KEY, relation);
    return __id;
  };

  QRelation.prototype.findById = function(__id) {
    var relation;
    if (relation = this.storage.get(this.KEY)) {
      return __indexOf.call(relation, __id) >= 0;
    }
    return false;
  };

  return QRelation;

})();
